#pragma once
#define PEDAL_SENSOR_ONE_PIN 10
#define PEDAL_SENSOR_TWO_PIN 11
#define PEDAL_CONTROL_SIGNAL_ONE_PIN 12
#define PEDAL_CONTROL_SIGNAL_TWO_PIN 13


#define STEER_SENSOR_ONE_PIN 8
#define STEER_SENSOR_TWO_PIN 9
#define STEER_CONTROL_SIGNAL_I2C0_SDA 20
#define STEER_CONTROL_SIGNAL_I2C0_SCL 21

#define BAUD_RATE 115200
#define SENSOR_INPUT_INTERVAL 5